# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/gustavboberg/c++spel

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/gustavboberg/c++spel

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/gustavboberg/c++spel/CMakeFiles /Users/gustavboberg/c++spel//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/gustavboberg/c++spel/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named CPPGame

# Build rule for target.
CPPGame: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CPPGame
.PHONY : CPPGame

# fast build rule for target.
CPPGame/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CPPGame.dir/build.make CMakeFiles/CPPGame.dir/build
.PHONY : CPPGame/fast

src/City.o: src/City.cpp.o
.PHONY : src/City.o

# target to build an object file
src/City.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CPPGame.dir/build.make CMakeFiles/CPPGame.dir/src/City.cpp.o
.PHONY : src/City.cpp.o

src/City.i: src/City.cpp.i
.PHONY : src/City.i

# target to preprocess a source file
src/City.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CPPGame.dir/build.make CMakeFiles/CPPGame.dir/src/City.cpp.i
.PHONY : src/City.cpp.i

src/City.s: src/City.cpp.s
.PHONY : src/City.s

# target to generate assembly for a file
src/City.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CPPGame.dir/build.make CMakeFiles/CPPGame.dir/src/City.cpp.s
.PHONY : src/City.cpp.s

src/Game.o: src/Game.cpp.o
.PHONY : src/Game.o

# target to build an object file
src/Game.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CPPGame.dir/build.make CMakeFiles/CPPGame.dir/src/Game.cpp.o
.PHONY : src/Game.cpp.o

src/Game.i: src/Game.cpp.i
.PHONY : src/Game.i

# target to preprocess a source file
src/Game.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CPPGame.dir/build.make CMakeFiles/CPPGame.dir/src/Game.cpp.i
.PHONY : src/Game.cpp.i

src/Game.s: src/Game.cpp.s
.PHONY : src/Game.s

# target to generate assembly for a file
src/Game.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CPPGame.dir/build.make CMakeFiles/CPPGame.dir/src/Game.cpp.s
.PHONY : src/Game.cpp.s

src/Hexagon.o: src/Hexagon.cpp.o
.PHONY : src/Hexagon.o

# target to build an object file
src/Hexagon.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CPPGame.dir/build.make CMakeFiles/CPPGame.dir/src/Hexagon.cpp.o
.PHONY : src/Hexagon.cpp.o

src/Hexagon.i: src/Hexagon.cpp.i
.PHONY : src/Hexagon.i

# target to preprocess a source file
src/Hexagon.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CPPGame.dir/build.make CMakeFiles/CPPGame.dir/src/Hexagon.cpp.i
.PHONY : src/Hexagon.cpp.i

src/Hexagon.s: src/Hexagon.cpp.s
.PHONY : src/Hexagon.s

# target to generate assembly for a file
src/Hexagon.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CPPGame.dir/build.make CMakeFiles/CPPGame.dir/src/Hexagon.cpp.s
.PHONY : src/Hexagon.cpp.s

src/InputHandler.o: src/InputHandler.cpp.o
.PHONY : src/InputHandler.o

# target to build an object file
src/InputHandler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CPPGame.dir/build.make CMakeFiles/CPPGame.dir/src/InputHandler.cpp.o
.PHONY : src/InputHandler.cpp.o

src/InputHandler.i: src/InputHandler.cpp.i
.PHONY : src/InputHandler.i

# target to preprocess a source file
src/InputHandler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CPPGame.dir/build.make CMakeFiles/CPPGame.dir/src/InputHandler.cpp.i
.PHONY : src/InputHandler.cpp.i

src/InputHandler.s: src/InputHandler.cpp.s
.PHONY : src/InputHandler.s

# target to generate assembly for a file
src/InputHandler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CPPGame.dir/build.make CMakeFiles/CPPGame.dir/src/InputHandler.cpp.s
.PHONY : src/InputHandler.cpp.s

src/Player.o: src/Player.cpp.o
.PHONY : src/Player.o

# target to build an object file
src/Player.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CPPGame.dir/build.make CMakeFiles/CPPGame.dir/src/Player.cpp.o
.PHONY : src/Player.cpp.o

src/Player.i: src/Player.cpp.i
.PHONY : src/Player.i

# target to preprocess a source file
src/Player.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CPPGame.dir/build.make CMakeFiles/CPPGame.dir/src/Player.cpp.i
.PHONY : src/Player.cpp.i

src/Player.s: src/Player.cpp.s
.PHONY : src/Player.s

# target to generate assembly for a file
src/Player.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CPPGame.dir/build.make CMakeFiles/CPPGame.dir/src/Player.cpp.s
.PHONY : src/Player.cpp.s

src/buildings/Base.o: src/buildings/Base.cpp.o
.PHONY : src/buildings/Base.o

# target to build an object file
src/buildings/Base.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CPPGame.dir/build.make CMakeFiles/CPPGame.dir/src/buildings/Base.cpp.o
.PHONY : src/buildings/Base.cpp.o

src/buildings/Base.i: src/buildings/Base.cpp.i
.PHONY : src/buildings/Base.i

# target to preprocess a source file
src/buildings/Base.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CPPGame.dir/build.make CMakeFiles/CPPGame.dir/src/buildings/Base.cpp.i
.PHONY : src/buildings/Base.cpp.i

src/buildings/Base.s: src/buildings/Base.cpp.s
.PHONY : src/buildings/Base.s

# target to generate assembly for a file
src/buildings/Base.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CPPGame.dir/build.make CMakeFiles/CPPGame.dir/src/buildings/Base.cpp.s
.PHONY : src/buildings/Base.cpp.s

src/buildings/Building.o: src/buildings/Building.cpp.o
.PHONY : src/buildings/Building.o

# target to build an object file
src/buildings/Building.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CPPGame.dir/build.make CMakeFiles/CPPGame.dir/src/buildings/Building.cpp.o
.PHONY : src/buildings/Building.cpp.o

src/buildings/Building.i: src/buildings/Building.cpp.i
.PHONY : src/buildings/Building.i

# target to preprocess a source file
src/buildings/Building.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CPPGame.dir/build.make CMakeFiles/CPPGame.dir/src/buildings/Building.cpp.i
.PHONY : src/buildings/Building.cpp.i

src/buildings/Building.s: src/buildings/Building.cpp.s
.PHONY : src/buildings/Building.s

# target to generate assembly for a file
src/buildings/Building.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CPPGame.dir/build.make CMakeFiles/CPPGame.dir/src/buildings/Building.cpp.s
.PHONY : src/buildings/Building.cpp.s

src/buildings/CityCenter.o: src/buildings/CityCenter.cpp.o
.PHONY : src/buildings/CityCenter.o

# target to build an object file
src/buildings/CityCenter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CPPGame.dir/build.make CMakeFiles/CPPGame.dir/src/buildings/CityCenter.cpp.o
.PHONY : src/buildings/CityCenter.cpp.o

src/buildings/CityCenter.i: src/buildings/CityCenter.cpp.i
.PHONY : src/buildings/CityCenter.i

# target to preprocess a source file
src/buildings/CityCenter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CPPGame.dir/build.make CMakeFiles/CPPGame.dir/src/buildings/CityCenter.cpp.i
.PHONY : src/buildings/CityCenter.cpp.i

src/buildings/CityCenter.s: src/buildings/CityCenter.cpp.s
.PHONY : src/buildings/CityCenter.s

# target to generate assembly for a file
src/buildings/CityCenter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CPPGame.dir/build.make CMakeFiles/CPPGame.dir/src/buildings/CityCenter.cpp.s
.PHONY : src/buildings/CityCenter.cpp.s

src/buildings/ResidentialArea.o: src/buildings/ResidentialArea.cpp.o
.PHONY : src/buildings/ResidentialArea.o

# target to build an object file
src/buildings/ResidentialArea.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CPPGame.dir/build.make CMakeFiles/CPPGame.dir/src/buildings/ResidentialArea.cpp.o
.PHONY : src/buildings/ResidentialArea.cpp.o

src/buildings/ResidentialArea.i: src/buildings/ResidentialArea.cpp.i
.PHONY : src/buildings/ResidentialArea.i

# target to preprocess a source file
src/buildings/ResidentialArea.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CPPGame.dir/build.make CMakeFiles/CPPGame.dir/src/buildings/ResidentialArea.cpp.i
.PHONY : src/buildings/ResidentialArea.cpp.i

src/buildings/ResidentialArea.s: src/buildings/ResidentialArea.cpp.s
.PHONY : src/buildings/ResidentialArea.s

# target to generate assembly for a file
src/buildings/ResidentialArea.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CPPGame.dir/build.make CMakeFiles/CPPGame.dir/src/buildings/ResidentialArea.cpp.s
.PHONY : src/buildings/ResidentialArea.cpp.s

src/business/Proffesion.o: src/business/Proffesion.cpp.o
.PHONY : src/business/Proffesion.o

# target to build an object file
src/business/Proffesion.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CPPGame.dir/build.make CMakeFiles/CPPGame.dir/src/business/Proffesion.cpp.o
.PHONY : src/business/Proffesion.cpp.o

src/business/Proffesion.i: src/business/Proffesion.cpp.i
.PHONY : src/business/Proffesion.i

# target to preprocess a source file
src/business/Proffesion.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CPPGame.dir/build.make CMakeFiles/CPPGame.dir/src/business/Proffesion.cpp.i
.PHONY : src/business/Proffesion.cpp.i

src/business/Proffesion.s: src/business/Proffesion.cpp.s
.PHONY : src/business/Proffesion.s

# target to generate assembly for a file
src/business/Proffesion.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CPPGame.dir/build.make CMakeFiles/CPPGame.dir/src/business/Proffesion.cpp.s
.PHONY : src/business/Proffesion.cpp.s

src/business/workplaces/OilRefinery.o: src/business/workplaces/OilRefinery.cpp.o
.PHONY : src/business/workplaces/OilRefinery.o

# target to build an object file
src/business/workplaces/OilRefinery.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CPPGame.dir/build.make CMakeFiles/CPPGame.dir/src/business/workplaces/OilRefinery.cpp.o
.PHONY : src/business/workplaces/OilRefinery.cpp.o

src/business/workplaces/OilRefinery.i: src/business/workplaces/OilRefinery.cpp.i
.PHONY : src/business/workplaces/OilRefinery.i

# target to preprocess a source file
src/business/workplaces/OilRefinery.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CPPGame.dir/build.make CMakeFiles/CPPGame.dir/src/business/workplaces/OilRefinery.cpp.i
.PHONY : src/business/workplaces/OilRefinery.cpp.i

src/business/workplaces/OilRefinery.s: src/business/workplaces/OilRefinery.cpp.s
.PHONY : src/business/workplaces/OilRefinery.s

# target to generate assembly for a file
src/business/workplaces/OilRefinery.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CPPGame.dir/build.make CMakeFiles/CPPGame.dir/src/business/workplaces/OilRefinery.cpp.s
.PHONY : src/business/workplaces/OilRefinery.cpp.s

src/business/workplaces/Workplace.o: src/business/workplaces/Workplace.cpp.o
.PHONY : src/business/workplaces/Workplace.o

# target to build an object file
src/business/workplaces/Workplace.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CPPGame.dir/build.make CMakeFiles/CPPGame.dir/src/business/workplaces/Workplace.cpp.o
.PHONY : src/business/workplaces/Workplace.cpp.o

src/business/workplaces/Workplace.i: src/business/workplaces/Workplace.cpp.i
.PHONY : src/business/workplaces/Workplace.i

# target to preprocess a source file
src/business/workplaces/Workplace.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CPPGame.dir/build.make CMakeFiles/CPPGame.dir/src/business/workplaces/Workplace.cpp.i
.PHONY : src/business/workplaces/Workplace.cpp.i

src/business/workplaces/Workplace.s: src/business/workplaces/Workplace.cpp.s
.PHONY : src/business/workplaces/Workplace.s

# target to generate assembly for a file
src/business/workplaces/Workplace.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CPPGame.dir/build.make CMakeFiles/CPPGame.dir/src/business/workplaces/Workplace.cpp.s
.PHONY : src/business/workplaces/Workplace.cpp.s

src/characters/Character.o: src/characters/Character.cpp.o
.PHONY : src/characters/Character.o

# target to build an object file
src/characters/Character.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CPPGame.dir/build.make CMakeFiles/CPPGame.dir/src/characters/Character.cpp.o
.PHONY : src/characters/Character.cpp.o

src/characters/Character.i: src/characters/Character.cpp.i
.PHONY : src/characters/Character.i

# target to preprocess a source file
src/characters/Character.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CPPGame.dir/build.make CMakeFiles/CPPGame.dir/src/characters/Character.cpp.i
.PHONY : src/characters/Character.cpp.i

src/characters/Character.s: src/characters/Character.cpp.s
.PHONY : src/characters/Character.s

# target to generate assembly for a file
src/characters/Character.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CPPGame.dir/build.make CMakeFiles/CPPGame.dir/src/characters/Character.cpp.s
.PHONY : src/characters/Character.cpp.s

src/characters/Soldier.o: src/characters/Soldier.cpp.o
.PHONY : src/characters/Soldier.o

# target to build an object file
src/characters/Soldier.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CPPGame.dir/build.make CMakeFiles/CPPGame.dir/src/characters/Soldier.cpp.o
.PHONY : src/characters/Soldier.cpp.o

src/characters/Soldier.i: src/characters/Soldier.cpp.i
.PHONY : src/characters/Soldier.i

# target to preprocess a source file
src/characters/Soldier.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CPPGame.dir/build.make CMakeFiles/CPPGame.dir/src/characters/Soldier.cpp.i
.PHONY : src/characters/Soldier.cpp.i

src/characters/Soldier.s: src/characters/Soldier.cpp.s
.PHONY : src/characters/Soldier.s

# target to generate assembly for a file
src/characters/Soldier.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CPPGame.dir/build.make CMakeFiles/CPPGame.dir/src/characters/Soldier.cpp.s
.PHONY : src/characters/Soldier.cpp.s

src/graphics/GridFiller.o: src/graphics/GridFiller.cpp.o
.PHONY : src/graphics/GridFiller.o

# target to build an object file
src/graphics/GridFiller.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CPPGame.dir/build.make CMakeFiles/CPPGame.dir/src/graphics/GridFiller.cpp.o
.PHONY : src/graphics/GridFiller.cpp.o

src/graphics/GridFiller.i: src/graphics/GridFiller.cpp.i
.PHONY : src/graphics/GridFiller.i

# target to preprocess a source file
src/graphics/GridFiller.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CPPGame.dir/build.make CMakeFiles/CPPGame.dir/src/graphics/GridFiller.cpp.i
.PHONY : src/graphics/GridFiller.cpp.i

src/graphics/GridFiller.s: src/graphics/GridFiller.cpp.s
.PHONY : src/graphics/GridFiller.s

# target to generate assembly for a file
src/graphics/GridFiller.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CPPGame.dir/build.make CMakeFiles/CPPGame.dir/src/graphics/GridFiller.cpp.s
.PHONY : src/graphics/GridFiller.cpp.s

src/graphics/HexGrid.o: src/graphics/HexGrid.cpp.o
.PHONY : src/graphics/HexGrid.o

# target to build an object file
src/graphics/HexGrid.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CPPGame.dir/build.make CMakeFiles/CPPGame.dir/src/graphics/HexGrid.cpp.o
.PHONY : src/graphics/HexGrid.cpp.o

src/graphics/HexGrid.i: src/graphics/HexGrid.cpp.i
.PHONY : src/graphics/HexGrid.i

# target to preprocess a source file
src/graphics/HexGrid.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CPPGame.dir/build.make CMakeFiles/CPPGame.dir/src/graphics/HexGrid.cpp.i
.PHONY : src/graphics/HexGrid.cpp.i

src/graphics/HexGrid.s: src/graphics/HexGrid.cpp.s
.PHONY : src/graphics/HexGrid.s

# target to generate assembly for a file
src/graphics/HexGrid.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CPPGame.dir/build.make CMakeFiles/CPPGame.dir/src/graphics/HexGrid.cpp.s
.PHONY : src/graphics/HexGrid.cpp.s

src/graphics/Renderer.o: src/graphics/Renderer.cpp.o
.PHONY : src/graphics/Renderer.o

# target to build an object file
src/graphics/Renderer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CPPGame.dir/build.make CMakeFiles/CPPGame.dir/src/graphics/Renderer.cpp.o
.PHONY : src/graphics/Renderer.cpp.o

src/graphics/Renderer.i: src/graphics/Renderer.cpp.i
.PHONY : src/graphics/Renderer.i

# target to preprocess a source file
src/graphics/Renderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CPPGame.dir/build.make CMakeFiles/CPPGame.dir/src/graphics/Renderer.cpp.i
.PHONY : src/graphics/Renderer.cpp.i

src/graphics/Renderer.s: src/graphics/Renderer.cpp.s
.PHONY : src/graphics/Renderer.s

# target to generate assembly for a file
src/graphics/Renderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CPPGame.dir/build.make CMakeFiles/CPPGame.dir/src/graphics/Renderer.cpp.s
.PHONY : src/graphics/Renderer.cpp.s

src/graphics/VisibilitySystem.o: src/graphics/VisibilitySystem.cpp.o
.PHONY : src/graphics/VisibilitySystem.o

# target to build an object file
src/graphics/VisibilitySystem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CPPGame.dir/build.make CMakeFiles/CPPGame.dir/src/graphics/VisibilitySystem.cpp.o
.PHONY : src/graphics/VisibilitySystem.cpp.o

src/graphics/VisibilitySystem.i: src/graphics/VisibilitySystem.cpp.i
.PHONY : src/graphics/VisibilitySystem.i

# target to preprocess a source file
src/graphics/VisibilitySystem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CPPGame.dir/build.make CMakeFiles/CPPGame.dir/src/graphics/VisibilitySystem.cpp.i
.PHONY : src/graphics/VisibilitySystem.cpp.i

src/graphics/VisibilitySystem.s: src/graphics/VisibilitySystem.cpp.s
.PHONY : src/graphics/VisibilitySystem.s

# target to generate assembly for a file
src/graphics/VisibilitySystem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CPPGame.dir/build.make CMakeFiles/CPPGame.dir/src/graphics/VisibilitySystem.cpp.s
.PHONY : src/graphics/VisibilitySystem.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CPPGame.dir/build.make CMakeFiles/CPPGame.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CPPGame.dir/build.make CMakeFiles/CPPGame.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CPPGame.dir/build.make CMakeFiles/CPPGame.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/projectiles/projectile.o: src/projectiles/projectile.cpp.o
.PHONY : src/projectiles/projectile.o

# target to build an object file
src/projectiles/projectile.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CPPGame.dir/build.make CMakeFiles/CPPGame.dir/src/projectiles/projectile.cpp.o
.PHONY : src/projectiles/projectile.cpp.o

src/projectiles/projectile.i: src/projectiles/projectile.cpp.i
.PHONY : src/projectiles/projectile.i

# target to preprocess a source file
src/projectiles/projectile.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CPPGame.dir/build.make CMakeFiles/CPPGame.dir/src/projectiles/projectile.cpp.i
.PHONY : src/projectiles/projectile.cpp.i

src/projectiles/projectile.s: src/projectiles/projectile.cpp.s
.PHONY : src/projectiles/projectile.s

# target to generate assembly for a file
src/projectiles/projectile.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CPPGame.dir/build.make CMakeFiles/CPPGame.dir/src/projectiles/projectile.cpp.s
.PHONY : src/projectiles/projectile.cpp.s

src/resources/Oil.o: src/resources/Oil.cpp.o
.PHONY : src/resources/Oil.o

# target to build an object file
src/resources/Oil.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CPPGame.dir/build.make CMakeFiles/CPPGame.dir/src/resources/Oil.cpp.o
.PHONY : src/resources/Oil.cpp.o

src/resources/Oil.i: src/resources/Oil.cpp.i
.PHONY : src/resources/Oil.i

# target to preprocess a source file
src/resources/Oil.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CPPGame.dir/build.make CMakeFiles/CPPGame.dir/src/resources/Oil.cpp.i
.PHONY : src/resources/Oil.cpp.i

src/resources/Oil.s: src/resources/Oil.cpp.s
.PHONY : src/resources/Oil.s

# target to generate assembly for a file
src/resources/Oil.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CPPGame.dir/build.make CMakeFiles/CPPGame.dir/src/resources/Oil.cpp.s
.PHONY : src/resources/Oil.cpp.s

src/resources/Resource.o: src/resources/Resource.cpp.o
.PHONY : src/resources/Resource.o

# target to build an object file
src/resources/Resource.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CPPGame.dir/build.make CMakeFiles/CPPGame.dir/src/resources/Resource.cpp.o
.PHONY : src/resources/Resource.cpp.o

src/resources/Resource.i: src/resources/Resource.cpp.i
.PHONY : src/resources/Resource.i

# target to preprocess a source file
src/resources/Resource.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CPPGame.dir/build.make CMakeFiles/CPPGame.dir/src/resources/Resource.cpp.i
.PHONY : src/resources/Resource.cpp.i

src/resources/Resource.s: src/resources/Resource.cpp.s
.PHONY : src/resources/Resource.s

# target to generate assembly for a file
src/resources/Resource.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CPPGame.dir/build.make CMakeFiles/CPPGame.dir/src/resources/Resource.cpp.s
.PHONY : src/resources/Resource.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... CPPGame"
	@echo "... src/City.o"
	@echo "... src/City.i"
	@echo "... src/City.s"
	@echo "... src/Game.o"
	@echo "... src/Game.i"
	@echo "... src/Game.s"
	@echo "... src/Hexagon.o"
	@echo "... src/Hexagon.i"
	@echo "... src/Hexagon.s"
	@echo "... src/InputHandler.o"
	@echo "... src/InputHandler.i"
	@echo "... src/InputHandler.s"
	@echo "... src/Player.o"
	@echo "... src/Player.i"
	@echo "... src/Player.s"
	@echo "... src/buildings/Base.o"
	@echo "... src/buildings/Base.i"
	@echo "... src/buildings/Base.s"
	@echo "... src/buildings/Building.o"
	@echo "... src/buildings/Building.i"
	@echo "... src/buildings/Building.s"
	@echo "... src/buildings/CityCenter.o"
	@echo "... src/buildings/CityCenter.i"
	@echo "... src/buildings/CityCenter.s"
	@echo "... src/buildings/ResidentialArea.o"
	@echo "... src/buildings/ResidentialArea.i"
	@echo "... src/buildings/ResidentialArea.s"
	@echo "... src/business/Proffesion.o"
	@echo "... src/business/Proffesion.i"
	@echo "... src/business/Proffesion.s"
	@echo "... src/business/workplaces/OilRefinery.o"
	@echo "... src/business/workplaces/OilRefinery.i"
	@echo "... src/business/workplaces/OilRefinery.s"
	@echo "... src/business/workplaces/Workplace.o"
	@echo "... src/business/workplaces/Workplace.i"
	@echo "... src/business/workplaces/Workplace.s"
	@echo "... src/characters/Character.o"
	@echo "... src/characters/Character.i"
	@echo "... src/characters/Character.s"
	@echo "... src/characters/Soldier.o"
	@echo "... src/characters/Soldier.i"
	@echo "... src/characters/Soldier.s"
	@echo "... src/graphics/GridFiller.o"
	@echo "... src/graphics/GridFiller.i"
	@echo "... src/graphics/GridFiller.s"
	@echo "... src/graphics/HexGrid.o"
	@echo "... src/graphics/HexGrid.i"
	@echo "... src/graphics/HexGrid.s"
	@echo "... src/graphics/Renderer.o"
	@echo "... src/graphics/Renderer.i"
	@echo "... src/graphics/Renderer.s"
	@echo "... src/graphics/VisibilitySystem.o"
	@echo "... src/graphics/VisibilitySystem.i"
	@echo "... src/graphics/VisibilitySystem.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/projectiles/projectile.o"
	@echo "... src/projectiles/projectile.i"
	@echo "... src/projectiles/projectile.s"
	@echo "... src/resources/Oil.o"
	@echo "... src/resources/Oil.i"
	@echo "... src/resources/Oil.s"
	@echo "... src/resources/Resource.o"
	@echo "... src/resources/Resource.i"
	@echo "... src/resources/Resource.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

